before:
  hooks:
    - "go mod download"

builds:
  - skip: true

release:
  github:
    name: "go-option"
    owner: "auryannn"
  name_template: "{{.Version}}"
  prerelease: "auto"
  mode: "append"

changelog:
  disable: true
