name: "Codecov"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  codecov:
    runs-on: "ubuntu-latest"
    steps:
      - name: "⤵️ Checkout repository"
        uses: "actions/checkout@v4.1.1"

      - name: "☂️ Upload coverage reports to Codecov"
        uses: "codecov/codecov-action@v4.1.0"
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
          slug: "auryannn/go-option"
